apiVersion: batch/v1
kind: Job
metadata:
  name: pi1
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: pi2
    spec:
      containers:
      - name: pi3
        image: mybuilder:latest
        imagePullPolicy: IfNotPresent
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
        command: ["java","-version"]
      restartPolicy: Never